#!/usr/bin/env bash
# Auto-generated by install.py — do not edit manually
set -euo pipefail
cd "/home/user/Trials/options_signals"
LOG="/home/user/Trials/options_signals/logs/app.log"
echo "$(date -Iseconds)  Starting Options Trading Signals on port 8501" >> "$LOG"
exec /home/user/Trials/options_signals/.venv/bin/streamlit app.py \
    --server.port 8501 \
    --server.headless false \
    >> "$LOG" 2>&1
