#!/usr/bin/env bash
# Options Trading Signals — quick launcher (generated by install.py)
# Usage: ./launch.sh           → web UI
#        ./launch.sh terminal  → terminal dashboard
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

# Activate the venv created by install.py
if [ -f "/home/user/Trials/options_signals/.venv/bin/activate" ]; then
    # shellcheck disable=SC1090
    source "/home/user/Trials/options_signals/.venv/bin/activate"
fi

if [ "${1:-}" = "terminal" ]; then
    python terminal_app.py "${@:2}"
else
    echo "Starting Options Trading Signals → http://localhost:8501"
    "/home/user/Trials/options_signals/.venv/bin/streamlit" run app.py \
        --server.port 8501 \
        --server.headless false
fi
